version: '3'
services:
  riperis:
    image: "dockerhama/riperis:latest"
    command: "--plugin plugins.influx --host rrc21"
    volumes:
      - ./plugins:/bin/plugins
      - ./init:/opt/init
    networks:
      tik_net:

networks:
  tik_net:
    driver: bridge
