version: '3'
services:
  riperis:
    image: "dockerhama/riperis:latest"
    command: "--format influx --host rrc21"
    volumes:
      - ./plugins:/bin/plugins
    networks:
      tik_net:

networks:
  tik_net:
    driver: bridge
